// react-client/src/views/admin/users/edit.jsx
import { useState, useEffect } from 'react';
import SidebarMenu from '../../../components/SidebarMenu';

import { useNavigate, useParams } from 'react-router-dom';
import Cookies from 'js-cookie';
import Api from '../../../services/api';

// get token from cookies
const token = Cookies.get('token')

export default function UsersEdit() {

    const navigate = useNavigate();

    const { id } = useParams();

    //define state
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    //state validation
    const [validation, setValidation] = useState([]);

    // fetch detail user
    const fetchDetailUser = async () => {
        await Api.get(`/api/admin/users/${id}`)
                .then(response => {
                    setName(response.data.data.name);
                    setEmail(response.data.data.email);
                })
                .catch(error => {
                    console.error(error)
                })
    }

    // hook useEffect
    useEffect(() => {
        fetchDetailUser();
    }, [])

    const updateUser = async (e) => {
        e.preventDefault();

        await Api.put(`/api/admin/users/${id}`, {
            name: name,
            email: email,
            password: password
        })
            .then(() => {
                navigate('/admin/users')
            })
            .catch((error) => {
                setValidation(error.response.data)
            })
    }

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded shadow-sm">
                        <div class="card-header">
                            ADD USER
                        </div>
                        <div className="card-body">
                             {
                                validation.errors && (
                                    <div className="alert alert-danger mt-2 pb-0">
                                        {
                                            validation.errors.map((error, index) => (
                                                <p key={index}>{error.path} : {error.msg}</p>
                                            ))
                                        }
                                    </div>
                                )
                            }
                            <form onSubmit={updateUser}>

                                <div class="form-group mb-3">
                                    <label class="mb-1 fw-bold">Full Name</label>
                                    <input type="text" value={name} onChange={(e) => setName(e.target.value)} class="form-control" placeholder="Full Name" />
                                </div>

                                <div class="form-group mb-3">
                                    <label class="mb-1 fw-bold">Email address</label>
                                    <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} class="form-control"
                                        placeholder="Email Address" />
                                </div>

                                <div class="form-group mb-3">
                                    <label class="mb-1 fw-bold">Password</label>
                                    <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} class="form-control"
                                        placeholder="Password" />
                                </div>

                                <button type="submit" class="btn btn-sm btn-primary">UPDATE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

// vue-client/src/views/admin/users/edit.vue
<script setup>

//import sidebar component
import SidebarMenu from '../../../components/SidebarMenu.vue';

//import reactive and ref from vue
import { reactive, ref, onMounted } from 'vue';

//import useRouter from vue router
import { useRouter, useRoute } from 'vue-router'

//inisialisasi vue router on Composition API
const router = useRouter()

//inisialisasi vue router on Composition API
const route = useRoute();

//import js cookie
import Cookies from 'js-cookie';

//import api
import Api from '../../../services/api';

//get token from cookies
const token = Cookies.get('token');

const user = reactive({
    name: '',
    email: '',
    password: '',
})

const validation = ref([])

onMounted(async () => {
    Api.defaults.headers.common['Authorization'] = token

    await Api.get(`/api/admin/users/${route.params.id}`)
            .then(response => {
                user.name = response.data.data.name
                user.email = response.data.data.email
            })
})

const updateUser = async () => {
    Api.defaults.headers.common['Authorization'] = token

    await Api.put(`/api/admin/users/${route.params.id}`, {
        name: user.name,
        email: user.email,
        password: user.password
    })
        .then(() => {
            router.push({
                name: 'admin.users.index'
            })
        .catch(error => {
            validation.value = error.response.data
        })
        })
}

</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 rounded shadow-sm">
                    <div class="card-header">
                        EDIT USER
                    </div>
                    <div class="card-body">
                        <div v-if="validation.errors" class="mt-2 alert alert-danger">
                            <ul class="mt-0 mb-0">
                                <li v-for="(error, index) in validation.errors" :key="index">
                                    {{ `${error.path} : ${error.msg}` }}
                                </li>
                            </ul>
                        </div>
                        <form @submit.prevent="updateUser">

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Full Name</label>
                                <input type="text" v-model="user.name" class="form-control" placeholder="Full Name" />
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Email address</label>
                                <input type="email" v-model="user.email" class="form-control"
                                    placeholder="Email Address" />
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Password</label>
                                <input type="password" v-model="user.password" class="form-control"
                                    placeholder="Password" />
                            </div>

                            <button type="submit" class="btn btn-sm btn-primary">UPDATE</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
