// vue-client/src/components/SidebarMenu.vue
<script setup>

import { useRouter } from 'vue-router'
import Cookies from 'js-cookie'

const router = useRouter()

const logout = () => {
    Cookies.remove('token');
    Cookies.remove('user');

    router.push({ name: 'login' })
}

</script>

<template>
    <div class="card border-0 rounded shadow-sm">
        <div class="card-header">
            MAIN MENU
        </div>
        <div class="card-body">
            <div class="list-group">
                <router-link :to="{ name: 'dashboard' }" class="list-group-item list-group-item-action">Dashboard</router-link>
                <router-link :to="{ name: 'admin.users.index' }" class="list-group-item list-group-item-action">Users</router-link>
                <a href="#" @click="logout" class="list-group-item list-group-item-action">Logout</a>
            </div>
        </div>
    </div>
</template>

// react-client/src/components/SidebarMenu.jsx
//import Link from react router dom
import { Link, useNavigate } from "react-router-dom";
import React, { useContext } from "react";
import Cookies from "js-cookie";
import { AuthContext } from "../context/AuthContext";

export default function SidebarMenu() {
    const navigate = useNavigate()

    const { setIsAuth } = useContext(AuthContext)

    const logout = () => {
        Cookies.remove('token')
        Cookies.remove('user')

        setIsAuth(false)

        navigate('/login', { replace: true })
    }

    return (
        <div className="card border-0 rounded shadow-sm">
            <div className="card-header">
                MAIN MENU
            </div>
            <div className="card-body">
                <div className="list-group">
                    <Link to="/admin/dashboard" className="list-group-item list-group-item-action">Dashboard</Link>

                    <Link to="/admin/users" className="list-group-item list-group-item-action">Users</Link>
                    <a onClick={logout} className="list-group-item list-group-item-action" style={{ cursor: 'pointer' }}>Logout</a>
                </div>
            </div>
        </div>
    )
}
