// react-client/src/views/admin/dashboard/index.jsx
//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

import { useState, useEffect } from 'react';
import Cookies from 'js-cookie';

export default function Dashboard() {
    const [user, setUser] = useState([]);

    useEffect(() => {
        const userData = Cookies.get('user')

        console.log(userData)

        if (userData) {
            // assign user data to state "user"
            setUser(JSON.parse(userData))
        }
    }, [])

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded shadow-sm">
                        <div className="card-header">
                            DASHBOARD
                        </div>
                        <div className="card-body">
                            Selamat Datang, <strong>{ user?.name }</strong>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

// vue-client/src/views/admin/dashboard/index.vue
<script setup>
import { ref, onMounted } from 'vue' 

import SidebarMenu from '../../../components/SidebarMenu.vue'
import Cookies from 'js-cookie'

const user = ref(null)

onMounted(() => {
    const userData = Cookies.get('user')

    if (userData) {
        user.value = JSON.parse(userData)
    }

    console.log(user.value.name)
})

</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 rounded shadow-sm">
                    <div class="card-header">
                        DASHBOARD
                    </div>
                    <div class="card-body">
                        Selamat Datang, <strong>{{ user?.name }}</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
