// vue-client/src/views/admin/users/create.vue
<script setup>
import SidebarMenu from '../../../components/SidebarMenu.vue'

import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'

import Cookies from 'js-cookie'
import Api from '../../../services/api'

const router = useRouter();

const token = Cookies.get('token')

const user = reactive({
    name: '',
    email: '',
    password: '',
})

const validation = ref([])

const storeUser = async () => {
    Api.defaults.headers.common['Authorization'] = token

    await Api.post('/api/admin/users', {
        name: user.name,
        email: user.email,
        password: user.password 
    })
    .then(() => {
        router.push({
            name: 'admin.users.index'
        })
    })
    .catch(err => {
        validation.value = err.response.data
    })
}

</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 rounded shadow-sm">
                    <div class="card-header">
                        ADD USER
                    </div>
                    <div class="card-body">
                        <div v-if="validation.errors" class="mt-2 alert alert-danger">
                            <ul class="mt-0 mb-0">
                                <li v-for="(error, index) in validation.errors" :key="index">
                                    {{ `${error.path} : ${error.msg}` }}
                                </li>
                            </ul>
                        </div>
                        <form @submit.prevent="storeUser">

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Full Name</label>
                                <input type="text" v-model="user.name" class="form-control" placeholder="Full Name" />
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Email address</label>
                                <input type="email" v-model="user.email" class="form-control"
                                    placeholder="Email Address" />
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Password</label>
                                <input type="password" v-model="user.password" class="form-control"
                                    placeholder="Password" />
                            </div>

                            <button type="submit" class="btn btn-sm btn-primary">SAVE</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>  
</template>

// react-client/src/views/admin/users/create.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

import Cookies from 'js-cookie';
import Api from '../../../services/api';

const token = Cookies.get('token')

export default function UsersCreate() {

    const navigate = useNavigate();

    // define state
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    // state validation
    const [validation, setValidation] = useState([]);

    const storeUser = async (e) => {
        e.preventDefault();

        // call API
        Api.defaults.headers.common['Authorization'] = token;

        await Api.post('/api/admin/users', {
            name: name,
            email: email,
            password: password
        })
        .then(() => {
            navigate('/admin/users')
        })
        .catch(error => {
            setValidation(error.response.data)
        })
    }

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded shadow-sm">
                        <div class="card-header">
                            ADD USER
                        </div>
                        <div className="card-body">
                            {
                                validation.errors && (
                                    <div className='alert alert-danger mt-2 pb-0'>
                                        {
                                            validation.errors.map((error, index) => (
                                                <p key={index}>{ error.path } : { error.message }</p>
                                            ))
                                        }
                                    </div>
                                )
                            }
                            <form onSubmit={storeUser}>
                                <div class="form-group mb-3">
                                    <label class="mb-1 fw-bold">Full Name</label>
                                    <input type="text" value={name} onChange={(e) => setName(e.target.value)} class="form-control" placeholder="Full Name" />
                                </div>

                                <div class="form-group mb-3">
                                    <label class="mb-1 fw-bold">Email address</label>
                                    <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} class="form-control"
                                        placeholder="Email Address" />
                                </div>

                                <div class="form-group mb-3">
                                    <label class="mb-1 fw-bold">Password</label>
                                    <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} class="form-control"
                                        placeholder="Password" />
                                </div>

                                <button type="submit" class="btn btn-sm btn-primary">SAVE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
