// react-client/src/views/auth/register.jsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Api from '../../services/api'

export default function Register() {
    const navigate = useNavigate();

    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    
    const [validation, setValidation] = useState([]);

    const register = async (e) => {
        e.preventDefault()

        await Api.post('/api/register', {
            name: name,
            email: email,
            password: password
        })
        .then(() => {
            console.log({ name, email, password })

            navigate('/login')
        })
        .catch(error => {
            setValidation(error.response.data)
        })
    }

    return (
       <div className="row justify-content-center">
        <div className="row justify-content-center">
            <div className="col-md-5">
                <div className="card border-0 rounded shadow-sm">
                    <div className="card-body">
                        <h4>REGISTER</h4>
                        <hr />
                        {
                            validation.errors && (
                                <div className='alert alert-danger mt-2 pb-0'>
                                    {
                                        validation.errors.map((error, index) => (
                                            <p key={index}>{error.path} : {error.msg}</p>
                                        ))
                                    }
                                </div>
                            )
                        }
                        <form onSubmit={register}>
                            <div className="row">
                                <div className="col-md-12 mb-3">
                                    <div className="form-group">
                                        <label className='mb-1 fw-bold' htmlFor="name">Name</label>
                                        <input type="text" className="form-control" id="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Masukkan name" />
                                    </div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-md-6 mb-3">
                                    <div className="form-group">
                                        <label className='mb-1 fw-bold' htmlFor="email">Email</label>
                                        <input type="email" className="form-control" id="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Masukkan email" />
                                    </div>
                                </div>
                                <div className="col-md-6 mb-3">
                                    <div className="form-group">
                                        <label className='mb-1 fw-bold' htmlFor="password">Password</label>
                                        <input type="password" className="form-control" id="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Masukkan password" />
                                    </div>
                                </div>
                            </div>
                            <button type="submit" className="btn btn-primary">REGISTER</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
       </div>
    )
}

// vue-client/src/views/auth/register.vue
<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'

import Api from '../../services/api'

const router = useRouter()

const user = reactive({
    name: '',
    email: '',
    password: '',
    password_confirmation: ''
})

const validation = ref([])

const register = async () => {
    await Api.post('/api/register', {
        name: user.name,
        email: user.email,
        password: user.password
    })
        .then(() => {
            router.push({
                name: 'login'
            })
        })
        .catch(error => {
            validation.value = error.response.data
        })
}


</script>

<template>
    <div class="row justify-content-center">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="card border-0 rounded shadow-sm">
                    <div class="card-body">
                        <h4>REGISTER</h4>
                        <hr>
                        <div v-if="validation.errors" class="mt-2 alert alert-danger">
                            <ul class="mt-0 mb-0">
                                <li v-for="(error, index) in validation.errors" :key="index">
                                    {{ `${error.path} : ${error.msg}` }}
                                </li>
                            </ul>
                        </div>
                        <form @submit.prevent="register">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <div class="form-group">
                                        <label class="mb-1 fw-bold">Full Name</label>
                                        <input type="text" v-model="user.name" class="form-control"
                                            placeholder="Full Name" />
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <div class="form-group">
                                        <label class="mb-1 fw-bold">Email address</label>
                                        <input type="email" v-model="user.email" class="form-control"
                                            placeholder="Email Address" />
                                    </div>

                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="form-group">
                                        <label class="mb-1 fw-bold">Password</label>
                                        <input type="password" v-model="user.password" class="form-control"
                                            placeholder="Password" />
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">REGISTER</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
